export const columns = [
  {
      "field": "missingDates",
      "headerName": "",
      "width": 16,
      "minWidth": 40,
      "maxWidth": 90,
      "align": "right",
      "padding": 0,
      "sortable": false,
      "headerClassName": "super-app-theme--header",
      "disableReorder": true,
      "resizable": false
  },
  {
      "field": "comment",
      "headerName": "",
      "width": 25,
      "minWidth": 16,
      "maxWidth": 48,
      "align": "left",
      "padding": 0,
      "sortable": false,
      "headerClassName": "super-app-theme--header",
      "disableReorder": true,
      "resizable": false
  },
  {
      "field": "firstColumn",
      "headerName": "firstColumn",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "2ad01a35-448b-4e8f-9beb-91add5aaa07b"
  },
  {
      "field": "secondColumn",
      "headerName": "secondColumn",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header",
      "cellClassName": "super-app-theme--cell",
      "bgColor": false,
      "id": "7a9e557f-fc5d-40fc-b760-391c2e77e31a"
  },
  {
      "field": "thirdColumn",
      "headerName": "thirdColumn (%)",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "053011e1-f2e6-45aa-a71d-919868ac0b9a"
  },
  {
      "field": "thirteenthColumn",
      "headerName": "thirteenthColumn",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header",
      "cellClassName": "super-app-theme--cell",
      "bgColor": false,
      "id": "95edd181-487b-4040-962d-d74633f4eff2"
  },
  {
      "field": "fourthColumn",
      "headerName": "fourteenthColumn ($)",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "b0780f88-e80e-4a9c-ae38-8aacf97fe60e"
  },
  {
      "field": "fourthColumnBudget",
      "headerName": "fourteenthColumn ($) -Budget",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header",
      "cellClassName": "super-app-theme--cell",
      "bgColor": false,
      "id": "f1c812e1-3310-40b6-ab82-2eaa87001163"
  },
  {
      "field": "fourthColumnVarianceToBudget",
      "headerName": "fourteenthColumn ($) -Variance to Budget",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "e1c9fc51-5433-4b9b-96fa-e7e5e2909b24"
  },
  {
      "field": "fourthColumnForecast",
      "headerName": "fourteenthColumn ($) -Forecast",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header",
      "cellClassName": "super-app-theme--cell",
      "bgColor": false,
      "id": "0b65cbca-a439-4b5d-bb03-4be658e5d97b"
  },
  {
      "field": "fourthColumnVarianceToForecast",
      "headerName": "fourteenthColumn ($) -Variance to Forecast",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "220bc756-4295-466e-b4e3-c639cef0f85f"
  },
  {
      "field": "fifthColumn",
      "headerName": "fifthColumn ($)",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header",
      "cellClassName": "super-app-theme--cell",
      "bgColor": false,
      "id": "78f34f1a-5036-4610-b623-c88590187a6c"
  },
  {
      "field": "fifthColumnpar",
      "headerName": "fifthColumnPAR ($)",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "9486a7e7-303b-4bb5-954d-72d34b4fd0a4"
  },
  {
      "field": "sixthColumn",
      "headerName": "sixthColumn ($)",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header",
      "cellClassName": "super-app-theme--cell",
      "bgColor": false,
      "id": "d6b2dd97-1b40-446d-88b7-04aecc2ecba0"
  },
  {
      "field": "seventhColumn",
      "headerName": "seventhColumn ($)",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "530d79ba-dce4-4457-b494-c6795fa31cf8"
  },
  {
      "field": "eightColumn",
      "headerName": "eightColumn",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header",
      "cellClassName": "super-app-theme--cell",
      "bgColor": false,
      "id": "947c31ad-2a02-45e9-a884-cb8efc619934"
  },
  {
      "field": "ninethColumn",
      "headerName": "ninethColumn",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "6bb6e264-f1ee-458f-aef8-7008cc070c01"
  },
  {
      "field": "tenthColumn",
      "headerName": "tenthColumn",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header",
      "cellClassName": "super-app-theme--cell",
      "bgColor": false,
      "id": "e899de9e-da91-447f-94e6-44675358d1d9"
  },
  {
      "field": "eleventhColumn",
      "headerName": "eleventhColumn",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "73c1271f-06d7-4318-99ba-10a1c59fbe34"
  },
  {
      "field": "twelvethColumn",
      "headerName": "twelvethColumn",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header",
      "cellClassName": "super-app-theme--cell",
      "bgColor": false,
      "id": "d6634f77-907f-42ad-ad90-580218f5c69c"
  },
  {
      "field": "test",
      "headerName": "test",
      "width": 175,
      "minWidth": 150,
      "align": "right",
      "sortable": true,
      "disableReorder": true,
      "resizable": false,
      "headerClassName": "super-app-theme--header-blue",
      "cellClassName": "super-app-theme--cell-value",
      "bgColor": true,
      "id": "2e1fe55a-2af1-4030-9227-7ba1e9521acc"
  }
]

export const rows = [
  {
      "id": 0,
      "path": [
          "x man"
      ],
      "firstColumn": "23,440",
      "secondColumn": "0",
      "thirdColumn": "0.00%",
      "thirteenthColumn": "$0.00",
      "fourthColumn": "1,714,738.66",
      "fourthColumnBudget": "759,472.00",
      "fourthColumnVarianceToBudget": "0.00",
      "fourthColumnForecast": "697,952.00",
      "fourthColumnVarianceToForecast": "1,714,738.66",
      "fifthColumn": "2,457,636.61",
      "fifthColumnpar": "$104.85",
      "sixthColumn": "$0.00",
      "seventhColumn": "$0.00",
      "eightColumn": "0",
      "ninethColumn": "0.00",
      "tenthColumn": "0.00",
      "eleventhColumn": "0.00",
      "twelvethColumn": "0.00",
      "test": "0.00",
      "compareValues": [
          0,
          0,
          0.5681818181818182,
          72.29234620689655,
          0,
          0,
          0,
          0,
          0,
          0,
          26.780882836990592,
          13.640706896551723,
          7.750401645768025,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "compareChangePercentages": [
          0,
          0,
          -1,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          2.9150306911279835,
          null,
          -1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "compareChangeValues": [
          0,
          0,
          0.5681818181818182,
          72.29234620689655,
          0,
          0,
          0,
          0,
          0,
          0,
          -78.06709540533024,
          13.640706896551723,
          7.750401645768025,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "performanceColumnIds": [],
      "values": [
          23440,
          0,
          0,
          null,
          1714738.66,
          759472,
          null,
          697952,
          1714738.66,
          2457636.61,
          104.84797824232082,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "valueTypeIds": [
          1,
          1,
          3,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
      ],
      "isTotal": true
  },
  {
      "id": 1,
      "path": [
          "x man",
          "y man"
      ],
      "firstColumn": "0",
      "secondColumn": "0",
      "thirdColumn": "0.00%",
      "thirteenthColumn": "$0.00",
      "fourthColumn": "0.00",
      "fourthColumnBudget": "0.00",
      "fourthColumnVarianceToBudget": "0.00",
      "fourthColumnForecast": "0.00",
      "fourthColumnVarianceToForecast": "0.00",
      "fifthColumn": "0.00",
      "fifthColumnpar": "$0.00",
      "sixthColumn": "$0.00",
      "seventhColumn": "$0.00",
      "eightColumn": "0",
      "ninethColumn": "0.00",
      "tenthColumn": "0.00",
      "eleventhColumn": "0.00",
      "twelvethColumn": "0.00",
      "test": "0.00",
      "compareValues": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "compareChangePercentages": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "compareChangeValues": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "performanceColumnIds": [],
      "title": null,
      "date": null,
      "hotelId": 4827,
      "priority": null,
      "value": null,
      "valueTypeId": null,
      "values": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "valueTypeIds": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
      ],
      "hotel": {
          "hotelName": "y man"
      }
  },
  
  
  {
      "id": 14,
      "path": [
          "x man",
          "z man"
      ],
      "firstColumn": "0",
      "secondColumn": "0",
      "thirdColumn": "0.00%",
      "thirteenthColumn": "$0.00",
      "fourthColumn": "0.00",
      "fourthColumnBudget": "0.00",
      "fourthColumnVarianceToBudget": "0.00",
      "fourthColumnForecast": "0.00",
      "fourthColumnVarianceToForecast": "0.00",
      "fifthColumn": "0.00",
      "fifthColumnpar": "$0.00",
      "sixthColumn": "$0.00",
      "seventhColumn": "$0.00",
      "eightColumn": "0",
      "ninethColumn": "0.00",
      "tenthColumn": "0.00",
      "eleventhColumn": "0.00",
      "twelvethColumn": "0.00",
      "test": "0.00",
      "compareValues": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "compareChangePercentages": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "compareChangeValues": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "performanceColumnIds": [],
      "title": null,
      "date": null,
      "hotelId": 4826,
      "priority": null,
      "value": null,
      "valueTypeId": null,
      "values": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "valueTypeIds": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
      ],
      "hotel": {
          "hotelName": "z man"
      }
  },
  {
      "id": 15,
      "path": [
          "R man"
      ],
      "firstColumn": "0",
      "secondColumn": "0",
      "thirdColumn": "0.00%",
      "thirteenthColumn": "$0.00",
      "fourthColumn": "248,836.74",
      "fourthColumnBudget": "0.00",
      "fourthColumnVarianceToBudget": "0.00",
      "fourthColumnForecast": "0.00",
      "fourthColumnVarianceToForecast": "248,836.74",
      "fifthColumn": "910,854.41",
      "fifthColumnpar": "$0.00",
      "sixthColumn": "$0.00",
      "seventhColumn": "$0.00",
      "eightColumn": "0",
      "ninethColumn": "0.00",
      "tenthColumn": "0.00",
      "eleventhColumn": "0.00",
      "twelvethColumn": "0.00",
      "test": "0.00",
      "compareValues": [
          0,
          0,
          0.8524038461538461,
          117.9697461928934,
          0,
          0,
          0,
          0,
          0,
          0,
          13.102033653846151,
          45.90159616469261,
          39.126697115384616,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "compareChangePercentages": [
          0,
          0,
          null,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          null,
          null,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "compareChangeValues": [
          0,
          0,
          0.8524038461538461,
          117.9697461928934,
          0,
          0,
          0,
          0,
          0,
          0,
          13.102033653846151,
          45.90159616469261,
          39.126697115384616,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "performanceColumnIds": [],
      "values": [
          0,
          0,
          null,
          null,
          248836.74,
          0,
          null,
          0,
          248836.74,
          910854.41,
          null,
          null,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "valueTypeIds": [
          1,
          1,
          3,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
      ],
      "isTotal": true
  },
  {
      "id": 16,
      "path": [
          "R man",
          "T man"
      ],
      "firstColumn": "0",
      "secondColumn": "0",
      "thirdColumn": "0.00%",
      "thirteenthColumn": "$0.00",
      "fourthColumn": "248,836.74",
      "fourthColumnBudget": "0.00",
      "fourthColumnVarianceToBudget": "0.00",
      "fourthColumnForecast": "0.00",
      "fourthColumnVarianceToForecast": "248,836.74",
      "fifthColumn": "910,854.41",
      "fifthColumnpar": "$0.00",
      "sixthColumn": "$0.00",
      "seventhColumn": "$0.00",
      "eightColumn": "0",
      "ninethColumn": "0.00",
      "tenthColumn": "0.00",
      "eleventhColumn": "0.00",
      "twelvethColumn": "0.00",
      "test": "0.00",
      "compareValues": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "compareChangePercentages": [
          null,
          null,
          null,
          null,
          0.18969359203627306,
          null,
          null,
          null,
          0.18969359203627306,
          32.423114732262285,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          0,
          null,
          null,
          null
      ],
      "compareChangeValues": [
          2080,
          1773,
          0.8524038461538461,
          117.9697461928934,
          -39676.380000000005,
          null,
          null,
          null,
          -39676.380000000005,
          -883602.18,
          13.102033653846151,
          45.90159616469261,
          39.126697115384616,
          17,
          868.55,
          14329.84,
          0,
          0,
          1987.05,
          17185.44,
          null
      ],
      "performanceColumnIds": [],
      "title": null,
      "date": null,
      "hotelId": 4409,
      "priority": null,
      "value": null,
      "valueTypeId": null,
      "values": [
          null,
          null,
          null,
          null,
          248836.74,
          null,
          null,
          null,
          248836.74,
          910854.41,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "valueTypeIds": [
          1,
          1,
          1,
          2,
          2,
          1,
          1,
          1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
      ],
      "hotel": {
          "hotelName": "T man"
      }
  },
  {
      "id": 17,
      "path": [
          "x man (Island)"
      ],
      "firstColumn": "0",
      "secondColumn": "0",
      "thirdColumn": "0.00%",
      "thirteenthColumn": "$0.00",
      "fourthColumn": "0.00",
      "fourthColumnBudget": "0.00",
      "fourthColumnVarianceToBudget": "0.00",
      "fourthColumnForecast": "0.00",
      "fourthColumnVarianceToForecast": "0.00",
      "fifthColumn": "0.00",
      "fifthColumnpar": "$0.00",
      "sixthColumn": "$0.00",
      "seventhColumn": "$0.00",
      "eightColumn": "0",
      "ninethColumn": "0.00",
      "tenthColumn": "0.00",
      "eleventhColumn": "0.00",
      "twelvethColumn": "0.00",
      "test": "0.00",
      "compareValues": [
          0,
          0,
          0.7044270833333334,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "compareChangePercentages": [
          0,
          0,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "compareChangeValues": [
          0,
          0,
          0.7044270833333334,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "performanceColumnIds": [],
      "values": [
          0,
          0,
          null,
          null,
          0,
          0,
          null,
          0,
          0,
          0,
          null,
          null,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "valueTypeIds": [
          1,
          1,
          3,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
      ],
      "isTotal": true
  },
  {
      "id": 18,
      "path": [
          "x man (Island)",
          "e man"
      ],
      "firstColumn": "0",
      "secondColumn": "0",
      "thirdColumn": "0.00%",
      "thirteenthColumn": "$0.00",
      "fourthColumn": "0.00",
      "fourthColumnBudget": "0.00",
      "fourthColumnVarianceToBudget": "0.00",
      "fourthColumnForecast": "0.00",
      "fourthColumnVarianceToForecast": "0.00",
      "fifthColumn": "0.00",
      "fifthColumnpar": "$0.00",
      "sixthColumn": "$0.00",
      "seventhColumn": "$0.00",
      "eightColumn": "0",
      "ninethColumn": "0.00",
      "tenthColumn": "0.00",
      "eleventhColumn": "0.00",
      "twelvethColumn": "0.00",
      "test": "0.00",
      "compareValues": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "compareChangePercentages": [
          null,
          null,
          null,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          0,
          0,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "compareChangeValues": [
          1536,
          827,
          0.5384114583333334,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          0,
          0,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "performanceColumnIds": [],
      "title": null,
      "date": null,
      "hotelId": 4934,
      "priority": null,
      "value": null,
      "valueTypeId": null,
      "values": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
      ],
      "valueTypeIds": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
      ],
      "hotel": {
          "hotelName": "e man"
      }
  },
  
  {
      "id": 20,
      "path": [
          "Group Not Assigned"
      ],
      "firstColumn": "0",
      "secondColumn": "0",
      "thirdColumn": "0.00%",
      "thirteenthColumn": "$0.00",
      "fourthColumn": "0.00",
      "fourthColumnBudget": "0.00",
      "fourthColumnVarianceToBudget": "0.00",
      "fourthColumnForecast": "0.00",
      "fourthColumnVarianceToForecast": "0.00",
      "fifthColumn": "0.00",
      "fifthColumnpar": "$0.00",
      "sixthColumn": "$0.00",
      "seventhColumn": "$0.00",
      "eightColumn": "0",
      "ninethColumn": "0.00",
      "tenthColumn": "0.00",
      "eleventhColumn": "0.00",
      "twelvethColumn": "0.00",
      "test": "0.00",
      "compareValues": [
          0,
          0,
          null,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          null,
          null,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "compareChangePercentages": [
          0,
          0,
          null,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          null,
          null,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "compareChangeValues": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "performanceColumnIds": [],
      "values": [
          0,
          0,
          null,
          null,
          0,
          0,
          null,
          0,
          0,
          0,
          null,
          null,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "valueTypeIds": [
          1,
          1,
          3,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
      ],
      "isTotal": true
  },
  {
      "id": 24,
      "path": [
          "Portfolio Total"
      ],
      "firstColumn": "23,440",
      "secondColumn": "0",
      "thirdColumn": "0.00%",
      "thirteenthColumn": "$0.00",
      "fourthColumn": "1,714,738.66",
      "fourthColumnBudget": "759,472.00",
      "fourthColumnVarianceToBudget": "0.00",
      "fourthColumnForecast": "697,952.00",
      "fourthColumnVarianceToForecast": "1,714,738.66",
      "fifthColumn": "2,457,636.61",
      "fifthColumnpar": "$104.85",
      "sixthColumn": "$0.00",
      "seventhColumn": "$0.00",
      "eightColumn": "0",
      "ninethColumn": "0.00",
      "tenthColumn": "0.00",
      "eleventhColumn": "0.00",
      "twelvethColumn": "0.00",
      "test": "0.00",
      "compareValues": [
          28592,
          16664,
          0.5828203693340794,
          62.904405904944795,
          1048239.02,
          383980,
          0,
          469708,
          1048239.02,
          683448.13,
          23.90347404868494,
          11.869314090254441,
          6.917678021824287,
          1117,
          63422.020000000004,
          92782.76999999999,
          23681.28,
          17989.77,
          3951.44,
          201827.28,
          0
      ],
      "compareChangePercentages": [
          0,
          0,
          -1,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          3.3863071128813207,
          null,
          -1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "compareChangeValues": [
          5152,
          16664,
          0.5828203693340794,
          62.904405904944795,
          -353274.6699999999,
          -346052,
          0,
          -228244,
          -353274.6699999999,
          -904791.4400000001,
          -80.94450419363588,
          11.869314090254441,
          6.917678021824287,
          1117,
          63422.020000000004,
          92782.76999999999,
          23681.28,
          17989.77,
          3951.44,
          201827.28,
          0
      ],
      "performanceColumnIds": [],
      "values": [
          23440,
          0,
          0,
          null,
          1714738.66,
          759472,
          0,
          697952,
          1714738.66,
          2457636.61,
          104.84797824232082,
          null,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
      ],
      "valueTypeIds": [
          1,
          1,
          3,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
      ],
      "isTotal": true
  }
]